apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  hcv.yaml: |
    api:
      addr: ":18080"
    grpc:
      addr: ":19090"
    log:
      level: {{ .Values.config.logLevel }}
      format: {{ .Values.config.logFormat }}
    etcd:
      endpoints: {{ .Values.config.etcdEndpoints | default "" }}
    storage:
      driver: {{ .Values.config.storageDriver }}
