{{- if .Values.etcd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-etcd
  labels:
    {{- include "hardcorevisor.labels" . | nindent 4 }}
    app.kubernetes.io/component: etcd
spec:
  type: ClusterIP
  ports:
    - port: 2379
      targetPort: client
      name: client
  selector:
    app.kubernetes.io/component: etcd
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
