// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: peripheral.proto

package peripheralpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceType int32

const (
	DeviceType_DEVICE_TYPE_UNSPECIFIED DeviceType = 0
	DeviceType_DEVICE_TYPE_GPU         DeviceType = 1
	DeviceType_DEVICE_TYPE_NIC         DeviceType = 2
	DeviceType_DEVICE_TYPE_USB         DeviceType = 3
	DeviceType_DEVICE_TYPE_DISK        DeviceType = 4
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "DEVICE_TYPE_UNSPECIFIED",
		1: "DEVICE_TYPE_GPU",
		2: "DEVICE_TYPE_NIC",
		3: "DEVICE_TYPE_USB",
		4: "DEVICE_TYPE_DISK",
	}
	DeviceType_value = map[string]int32{
		"DEVICE_TYPE_UNSPECIFIED": 0,
		"DEVICE_TYPE_GPU":         1,
		"DEVICE_TYPE_NIC":         2,
		"DEVICE_TYPE_USB":         3,
		"DEVICE_TYPE_DISK":        4,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_peripheral_proto_enumTypes[0].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_peripheral_proto_enumTypes[0]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{0}
}

type AttachDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmHandle      int32                  `protobuf:"varint,1,opt,name=vm_handle,json=vmHandle,proto3" json:"vm_handle,omitempty"`
	DeviceType    DeviceType             `protobuf:"varint,2,opt,name=device_type,json=deviceType,proto3,enum=hardcorevisor.peripheral.v1.DeviceType" json:"device_type,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Options       map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachDeviceRequest) Reset() {
	*x = AttachDeviceRequest{}
	mi := &file_peripheral_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachDeviceRequest) ProtoMessage() {}

func (x *AttachDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peripheral_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachDeviceRequest.ProtoReflect.Descriptor instead.
func (*AttachDeviceRequest) Descriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{0}
}

func (x *AttachDeviceRequest) GetVmHandle() int32 {
	if x != nil {
		return x.VmHandle
	}
	return 0
}

func (x *AttachDeviceRequest) GetDeviceType() DeviceType {
	if x != nil {
		return x.DeviceType
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

func (x *AttachDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AttachDeviceRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type AttachDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachDeviceResponse) Reset() {
	*x = AttachDeviceResponse{}
	mi := &file_peripheral_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachDeviceResponse) ProtoMessage() {}

func (x *AttachDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peripheral_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachDeviceResponse.ProtoReflect.Descriptor instead.
func (*AttachDeviceResponse) Descriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{1}
}

func (x *AttachDeviceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DetachDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmHandle      int32                  `protobuf:"varint,1,opt,name=vm_handle,json=vmHandle,proto3" json:"vm_handle,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachDeviceRequest) Reset() {
	*x = DetachDeviceRequest{}
	mi := &file_peripheral_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachDeviceRequest) ProtoMessage() {}

func (x *DetachDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peripheral_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachDeviceRequest.ProtoReflect.Descriptor instead.
func (*DetachDeviceRequest) Descriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{2}
}

func (x *DetachDeviceRequest) GetVmHandle() int32 {
	if x != nil {
		return x.VmHandle
	}
	return 0
}

func (x *DetachDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type DetachDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachDeviceResponse) Reset() {
	*x = DetachDeviceResponse{}
	mi := &file_peripheral_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachDeviceResponse) ProtoMessage() {}

func (x *DetachDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peripheral_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachDeviceResponse.ProtoReflect.Descriptor instead.
func (*DetachDeviceResponse) Descriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{3}
}

func (x *DetachDeviceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeFilter    DeviceType             `protobuf:"varint,1,opt,name=type_filter,json=typeFilter,proto3,enum=hardcorevisor.peripheral.v1.DeviceType" json:"type_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_peripheral_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peripheral_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{4}
}

func (x *ListDevicesRequest) GetTypeFilter() DeviceType {
	if x != nil {
		return x.TypeFilter
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceInfo          `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_peripheral_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peripheral_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{5}
}

func (x *ListDevicesResponse) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceType    DeviceType             `protobuf:"varint,2,opt,name=device_type,json=deviceType,proto3,enum=hardcorevisor.peripheral.v1.DeviceType" json:"device_type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PciAddress    string                 `protobuf:"bytes,4,opt,name=pci_address,json=pciAddress,proto3" json:"pci_address,omitempty"`
	AttachedVm    int32                  `protobuf:"varint,5,opt,name=attached_vm,json=attachedVm,proto3" json:"attached_vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_peripheral_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_peripheral_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_peripheral_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceInfo) GetDeviceType() DeviceType {
	if x != nil {
		return x.DeviceType
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

func (x *DeviceInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeviceInfo) GetPciAddress() string {
	if x != nil {
		return x.PciAddress
	}
	return ""
}

func (x *DeviceInfo) GetAttachedVm() int32 {
	if x != nil {
		return x.AttachedVm
	}
	return 0
}

var File_peripheral_proto protoreflect.FileDescriptor

const file_peripheral_proto_rawDesc = "" +
	"\n" +
	"\x10peripheral.proto\x12\x1bhardcorevisor.peripheral.v1\"\xae\x02\n" +
	"\x13AttachDeviceRequest\x12\x1b\n" +
	"\tvm_handle\x18\x01 \x01(\x05R\bvmHandle\x12H\n" +
	"\vdevice_type\x18\x02 \x01(\x0e2'.hardcorevisor.peripheral.v1.DeviceTypeR\n" +
	"deviceType\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12W\n" +
	"\aoptions\x18\x04 \x03(\v2=.hardcorevisor.peripheral.v1.AttachDeviceRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\x14AttachDeviceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"O\n" +
	"\x13DetachDeviceRequest\x12\x1b\n" +
	"\tvm_handle\x18\x01 \x01(\x05R\bvmHandle\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"0\n" +
	"\x14DetachDeviceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"^\n" +
	"\x12ListDevicesRequest\x12H\n" +
	"\vtype_filter\x18\x01 \x01(\x0e2'.hardcorevisor.peripheral.v1.DeviceTypeR\n" +
	"typeFilter\"X\n" +
	"\x13ListDevicesResponse\x12A\n" +
	"\adevices\x18\x01 \x03(\v2'.hardcorevisor.peripheral.v1.DeviceInfoR\adevices\"\xca\x01\n" +
	"\n" +
	"DeviceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12H\n" +
	"\vdevice_type\x18\x02 \x01(\x0e2'.hardcorevisor.peripheral.v1.DeviceTypeR\n" +
	"deviceType\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vpci_address\x18\x04 \x01(\tR\n" +
	"pciAddress\x12\x1f\n" +
	"\vattached_vm\x18\x05 \x01(\x05R\n" +
	"attachedVm*~\n" +
	"\n" +
	"DeviceType\x12\x1b\n" +
	"\x17DEVICE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fDEVICE_TYPE_GPU\x10\x01\x12\x13\n" +
	"\x0fDEVICE_TYPE_NIC\x10\x02\x12\x13\n" +
	"\x0fDEVICE_TYPE_USB\x10\x03\x12\x14\n" +
	"\x10DEVICE_TYPE_DISK\x10\x042\xef\x02\n" +
	"\x11PeripheralManager\x12s\n" +
	"\fAttachDevice\x120.hardcorevisor.peripheral.v1.AttachDeviceRequest\x1a1.hardcorevisor.peripheral.v1.AttachDeviceResponse\x12s\n" +
	"\fDetachDevice\x120.hardcorevisor.peripheral.v1.DetachDeviceRequest\x1a1.hardcorevisor.peripheral.v1.DetachDeviceResponse\x12p\n" +
	"\vListDevices\x12/.hardcorevisor.peripheral.v1.ListDevicesRequest\x1a0.hardcorevisor.peripheral.v1.ListDevicesResponseBIZGgithub.com/HardcoreMonk/hardcorevisor/controller/pkg/proto/peripheralpbb\x06proto3"

var (
	file_peripheral_proto_rawDescOnce sync.Once
	file_peripheral_proto_rawDescData []byte
)

func file_peripheral_proto_rawDescGZIP() []byte {
	file_peripheral_proto_rawDescOnce.Do(func() {
		file_peripheral_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peripheral_proto_rawDesc), len(file_peripheral_proto_rawDesc)))
	})
	return file_peripheral_proto_rawDescData
}

var file_peripheral_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_peripheral_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_peripheral_proto_goTypes = []any{
	(DeviceType)(0),              // 0: hardcorevisor.peripheral.v1.DeviceType
	(*AttachDeviceRequest)(nil),  // 1: hardcorevisor.peripheral.v1.AttachDeviceRequest
	(*AttachDeviceResponse)(nil), // 2: hardcorevisor.peripheral.v1.AttachDeviceResponse
	(*DetachDeviceRequest)(nil),  // 3: hardcorevisor.peripheral.v1.DetachDeviceRequest
	(*DetachDeviceResponse)(nil), // 4: hardcorevisor.peripheral.v1.DetachDeviceResponse
	(*ListDevicesRequest)(nil),   // 5: hardcorevisor.peripheral.v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),  // 6: hardcorevisor.peripheral.v1.ListDevicesResponse
	(*DeviceInfo)(nil),           // 7: hardcorevisor.peripheral.v1.DeviceInfo
	nil,                          // 8: hardcorevisor.peripheral.v1.AttachDeviceRequest.OptionsEntry
}
var file_peripheral_proto_depIdxs = []int32{
	0, // 0: hardcorevisor.peripheral.v1.AttachDeviceRequest.device_type:type_name -> hardcorevisor.peripheral.v1.DeviceType
	8, // 1: hardcorevisor.peripheral.v1.AttachDeviceRequest.options:type_name -> hardcorevisor.peripheral.v1.AttachDeviceRequest.OptionsEntry
	0, // 2: hardcorevisor.peripheral.v1.ListDevicesRequest.type_filter:type_name -> hardcorevisor.peripheral.v1.DeviceType
	7, // 3: hardcorevisor.peripheral.v1.ListDevicesResponse.devices:type_name -> hardcorevisor.peripheral.v1.DeviceInfo
	0, // 4: hardcorevisor.peripheral.v1.DeviceInfo.device_type:type_name -> hardcorevisor.peripheral.v1.DeviceType
	1, // 5: hardcorevisor.peripheral.v1.PeripheralManager.AttachDevice:input_type -> hardcorevisor.peripheral.v1.AttachDeviceRequest
	3, // 6: hardcorevisor.peripheral.v1.PeripheralManager.DetachDevice:input_type -> hardcorevisor.peripheral.v1.DetachDeviceRequest
	5, // 7: hardcorevisor.peripheral.v1.PeripheralManager.ListDevices:input_type -> hardcorevisor.peripheral.v1.ListDevicesRequest
	2, // 8: hardcorevisor.peripheral.v1.PeripheralManager.AttachDevice:output_type -> hardcorevisor.peripheral.v1.AttachDeviceResponse
	4, // 9: hardcorevisor.peripheral.v1.PeripheralManager.DetachDevice:output_type -> hardcorevisor.peripheral.v1.DetachDeviceResponse
	6, // 10: hardcorevisor.peripheral.v1.PeripheralManager.ListDevices:output_type -> hardcorevisor.peripheral.v1.ListDevicesResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_peripheral_proto_init() }
func file_peripheral_proto_init() {
	if File_peripheral_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peripheral_proto_rawDesc), len(file_peripheral_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_peripheral_proto_goTypes,
		DependencyIndexes: file_peripheral_proto_depIdxs,
		EnumInfos:         file_peripheral_proto_enumTypes,
		MessageInfos:      file_peripheral_proto_msgTypes,
	}.Build()
	File_peripheral_proto = out.File
	file_peripheral_proto_goTypes = nil
	file_peripheral_proto_depIdxs = nil
}
