// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: peripheral.proto

package peripheralpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PeripheralManager_AttachDevice_FullMethodName = "/hardcorevisor.peripheral.v1.PeripheralManager/AttachDevice"
	PeripheralManager_DetachDevice_FullMethodName = "/hardcorevisor.peripheral.v1.PeripheralManager/DetachDevice"
	PeripheralManager_ListDevices_FullMethodName  = "/hardcorevisor.peripheral.v1.PeripheralManager/ListDevices"
)

// PeripheralManagerClient is the client API for PeripheralManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PeripheralManagerClient interface {
	AttachDevice(ctx context.Context, in *AttachDeviceRequest, opts ...grpc.CallOption) (*AttachDeviceResponse, error)
	DetachDevice(ctx context.Context, in *DetachDeviceRequest, opts ...grpc.CallOption) (*DetachDeviceResponse, error)
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
}

type peripheralManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewPeripheralManagerClient(cc grpc.ClientConnInterface) PeripheralManagerClient {
	return &peripheralManagerClient{cc}
}

func (c *peripheralManagerClient) AttachDevice(ctx context.Context, in *AttachDeviceRequest, opts ...grpc.CallOption) (*AttachDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachDeviceResponse)
	err := c.cc.Invoke(ctx, PeripheralManager_AttachDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peripheralManagerClient) DetachDevice(ctx context.Context, in *DetachDeviceRequest, opts ...grpc.CallOption) (*DetachDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetachDeviceResponse)
	err := c.cc.Invoke(ctx, PeripheralManager_DetachDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peripheralManagerClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, PeripheralManager_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeripheralManagerServer is the server API for PeripheralManager service.
// All implementations must embed UnimplementedPeripheralManagerServer
// for forward compatibility.
type PeripheralManagerServer interface {
	AttachDevice(context.Context, *AttachDeviceRequest) (*AttachDeviceResponse, error)
	DetachDevice(context.Context, *DetachDeviceRequest) (*DetachDeviceResponse, error)
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	mustEmbedUnimplementedPeripheralManagerServer()
}

// UnimplementedPeripheralManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeripheralManagerServer struct{}

func (UnimplementedPeripheralManagerServer) AttachDevice(context.Context, *AttachDeviceRequest) (*AttachDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachDevice not implemented")
}
func (UnimplementedPeripheralManagerServer) DetachDevice(context.Context, *DetachDeviceRequest) (*DetachDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetachDevice not implemented")
}
func (UnimplementedPeripheralManagerServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedPeripheralManagerServer) mustEmbedUnimplementedPeripheralManagerServer() {}
func (UnimplementedPeripheralManagerServer) testEmbeddedByValue()                           {}

// UnsafePeripheralManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeripheralManagerServer will
// result in compilation errors.
type UnsafePeripheralManagerServer interface {
	mustEmbedUnimplementedPeripheralManagerServer()
}

func RegisterPeripheralManagerServer(s grpc.ServiceRegistrar, srv PeripheralManagerServer) {
	// If the following call panics, it indicates UnimplementedPeripheralManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PeripheralManager_ServiceDesc, srv)
}

func _PeripheralManager_AttachDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeripheralManagerServer).AttachDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeripheralManager_AttachDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeripheralManagerServer).AttachDevice(ctx, req.(*AttachDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeripheralManager_DetachDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeripheralManagerServer).DetachDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeripheralManager_DetachDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeripheralManagerServer).DetachDevice(ctx, req.(*DetachDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeripheralManager_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeripheralManagerServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeripheralManager_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeripheralManagerServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PeripheralManager_ServiceDesc is the grpc.ServiceDesc for PeripheralManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeripheralManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hardcorevisor.peripheral.v1.PeripheralManager",
	HandlerType: (*PeripheralManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AttachDevice",
			Handler:    _PeripheralManager_AttachDevice_Handler,
		},
		{
			MethodName: "DetachDevice",
			Handler:    _PeripheralManager_DetachDevice_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _PeripheralManager_ListDevices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "peripheral.proto",
}
