// Package ffi — CGo bindings to Rust vmcore staticlib
//
// Links against libvmcore.a (built by `cargo build -p vmcore --release`).
// All functions return i32: positive = success/handle, negative = error code.
//
// Build tag: only compiles when 'cgo_vmcore' tag is set.
// Usage: go build -tags cgo_vmcore ./pkg/ffi/...
//
//go:build cgo_vmcore

package ffi

/*
#cgo LDFLAGS: -L${SRCDIR}/../../../vmcore/target/release -lvmcore -ldl -lpthread -lm
#include <stdint.h>

// FFI function declarations (generated by cbindgen or manual)
extern int32_t hcv_init(void);
extern const char* hcv_version(void);
extern int32_t hcv_vm_create(void);
extern int32_t hcv_vm_destroy(int32_t handle);
*/
import "C"

import "unsafe"

func checkResult(code C.int32_t, op string) error {
	if code < 0 {
		return &FFIError{Code: int32(code), Op: op}
	}
	return nil
}

// Init initializes the vmcore library. Must be called once at startup.
func Init() error {
	return checkResult(C.hcv_init(), "init")
}

// Version returns the vmcore library version string.
func Version() string {
	cstr := C.hcv_version()
	return C.GoString(cstr)
}

// CreateVM creates a new VM instance. Returns the handle.
func CreateVM() (int32, error) {
	result := C.hcv_vm_create()
	if result < 0 {
		return 0, &FFIError{Code: int32(result), Op: "vm_create"}
	}
	return int32(result), nil
}

// DestroyVM destroys a VM instance by handle.
func DestroyVM(handle int32) error {
	return checkResult(C.hcv_vm_destroy(C.int32_t(handle)), "vm_destroy")
}

// Ensure unsafe import is used (required for CGo pointer rules)
var _ = unsafe.Pointer(nil)
