// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: compute.proto

package computepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VMState int32

const (
	VMState_VM_STATE_UNSPECIFIED VMState = 0
	VMState_VM_STATE_CREATED     VMState = 1
	VMState_VM_STATE_CONFIGURED  VMState = 2
	VMState_VM_STATE_RUNNING     VMState = 3
	VMState_VM_STATE_PAUSED      VMState = 4
	VMState_VM_STATE_STOPPED     VMState = 5
)

// Enum value maps for VMState.
var (
	VMState_name = map[int32]string{
		0: "VM_STATE_UNSPECIFIED",
		1: "VM_STATE_CREATED",
		2: "VM_STATE_CONFIGURED",
		3: "VM_STATE_RUNNING",
		4: "VM_STATE_PAUSED",
		5: "VM_STATE_STOPPED",
	}
	VMState_value = map[string]int32{
		"VM_STATE_UNSPECIFIED": 0,
		"VM_STATE_CREATED":     1,
		"VM_STATE_CONFIGURED":  2,
		"VM_STATE_RUNNING":     3,
		"VM_STATE_PAUSED":      4,
		"VM_STATE_STOPPED":     5,
	}
)

func (x VMState) Enum() *VMState {
	p := new(VMState)
	*p = x
	return p
}

func (x VMState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VMState) Descriptor() protoreflect.EnumDescriptor {
	return file_compute_proto_enumTypes[0].Descriptor()
}

func (VMState) Type() protoreflect.EnumType {
	return &file_compute_proto_enumTypes[0]
}

func (x VMState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VMState.Descriptor instead.
func (VMState) EnumDescriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{0}
}

type CreateVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vcpus         uint32                 `protobuf:"varint,2,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	MemoryMb      uint64                 `protobuf:"varint,3,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	TemplateId    string                 `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Disks         []*DiskSpec            `protobuf:"bytes,5,rep,name=disks,proto3" json:"disks,omitempty"`
	Nics          []*NicSpec             `protobuf:"bytes,6,rep,name=nics,proto3" json:"nics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMRequest) Reset() {
	*x = CreateVMRequest{}
	mi := &file_compute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMRequest) ProtoMessage() {}

func (x *CreateVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMRequest.ProtoReflect.Descriptor instead.
func (*CreateVMRequest) Descriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVMRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVMRequest) GetVcpus() uint32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *CreateVMRequest) GetMemoryMb() uint64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *CreateVMRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CreateVMRequest) GetDisks() []*DiskSpec {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *CreateVMRequest) GetNics() []*NicSpec {
	if x != nil {
		return x.Nics
	}
	return nil
}

type CreateVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            *VMInfo                `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMResponse) Reset() {
	*x = CreateVMResponse{}
	mi := &file_compute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMResponse) ProtoMessage() {}

func (x *CreateVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMResponse.ProtoReflect.Descriptor instead.
func (*CreateVMResponse) Descriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVMResponse) GetVm() *VMInfo {
	if x != nil {
		return x.Vm
	}
	return nil
}

type DestroyVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        int32                  `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyVMRequest) Reset() {
	*x = DestroyVMRequest{}
	mi := &file_compute_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyVMRequest) ProtoMessage() {}

func (x *DestroyVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compute_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyVMRequest.ProtoReflect.Descriptor instead.
func (*DestroyVMRequest) Descriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{2}
}

func (x *DestroyVMRequest) GetHandle() int32 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *DestroyVMRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DestroyVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyVMResponse) Reset() {
	*x = DestroyVMResponse{}
	mi := &file_compute_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyVMResponse) ProtoMessage() {}

func (x *DestroyVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compute_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyVMResponse.ProtoReflect.Descriptor instead.
func (*DestroyVMResponse) Descriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{3}
}

type VMActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        int32                  `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMActionRequest) Reset() {
	*x = VMActionRequest{}
	mi := &file_compute_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMActionRequest) ProtoMessage() {}

func (x *VMActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compute_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMActionRequest.ProtoReflect.Descriptor instead.
func (*VMActionRequest) Descriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{4}
}

func (x *VMActionRequest) GetHandle() int32 {
	if x != nil {
		return x.Handle
	}
	return 0
}

type VMActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewState      VMState                `protobuf:"varint,1,opt,name=new_state,json=newState,proto3,enum=hardcorevisor.compute.v1.VMState" json:"new_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMActionResponse) Reset() {
	*x = VMActionResponse{}
	mi := &file_compute_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMActionResponse) ProtoMessage() {}

func (x *VMActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compute_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMActionResponse.ProtoReflect.Descriptor instead.
func (*VMActionResponse) Descriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{5}
}

func (x *VMActionResponse) GetNewState() VMState {
	if x != nil {
		return x.NewState
	}
	return VMState_VM_STATE_UNSPECIFIED
}

type ListVMsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeFilter    string                 `protobuf:"bytes,1,opt,name=node_filter,json=nodeFilter,proto3" json:"node_filter,omitempty"`
	StateFilter   VMState                `protobuf:"varint,2,opt,name=state_filter,json=stateFilter,proto3,enum=hardcorevisor.compute.v1.VMState" json:"state_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsRequest) Reset() {
	*x = ListVMsRequest{}
	mi := &file_compute_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsRequest) ProtoMessage() {}

func (x *ListVMsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compute_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsRequest.ProtoReflect.Descriptor instead.
func (*ListVMsRequest) Descriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{6}
}

func (x *ListVMsRequest) GetNodeFilter() string {
	if x != nil {
		return x.NodeFilter
	}
	return ""
}

func (x *ListVMsRequest) GetStateFilter() VMState {
	if x != nil {
		return x.StateFilter
	}
	return VMState_VM_STATE_UNSPECIFIED
}

type ListVMsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VMInfo              `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsResponse) Reset() {
	*x = ListVMsResponse{}
	mi := &file_compute_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsResponse) ProtoMessage() {}

func (x *ListVMsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compute_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsResponse.ProtoReflect.Descriptor instead.
func (*ListVMsResponse) Descriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{7}
}

func (x *ListVMsResponse) GetVms() []*VMInfo {
	if x != nil {
		return x.Vms
	}
	return nil
}

type GetVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        int32                  `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMRequest) Reset() {
	*x = GetVMRequest{}
	mi := &file_compute_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMRequest) ProtoMessage() {}

func (x *GetVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compute_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMRequest.ProtoReflect.Descriptor instead.
func (*GetVMRequest) Descriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{8}
}

func (x *GetVMRequest) GetHandle() int32 {
	if x != nil {
		return x.Handle
	}
	return 0
}

type LiveMigrateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        int32                  `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	TargetNode    string                 `protobuf:"bytes,2,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveMigrateRequest) Reset() {
	*x = LiveMigrateRequest{}
	mi := &file_compute_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveMigrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveMigrateRequest) ProtoMessage() {}

func (x *LiveMigrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compute_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveMigrateRequest.ProtoReflect.Descriptor instead.
func (*LiveMigrateRequest) Descriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{9}
}

func (x *LiveMigrateRequest) GetHandle() int32 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *LiveMigrateRequest) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

type LiveMigrateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveMigrateResponse) Reset() {
	*x = LiveMigrateResponse{}
	mi := &file_compute_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveMigrateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveMigrateResponse) ProtoMessage() {}

func (x *LiveMigrateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compute_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveMigrateResponse.ProtoReflect.Descriptor instead.
func (*LiveMigrateResponse) Descriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{10}
}

func (x *LiveMigrateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LiveMigrateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VMInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        int32                  `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State         VMState                `protobuf:"varint,3,opt,name=state,proto3,enum=hardcorevisor.compute.v1.VMState" json:"state,omitempty"`
	Vcpus         uint32                 `protobuf:"varint,4,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	MemoryMb      uint64                 `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Node          string                 `protobuf:"bytes,6,opt,name=node,proto3" json:"node,omitempty"`
	Disks         []*DiskSpec            `protobuf:"bytes,7,rep,name=disks,proto3" json:"disks,omitempty"`
	Nics          []*NicSpec             `protobuf:"bytes,8,rep,name=nics,proto3" json:"nics,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMInfo) Reset() {
	*x = VMInfo{}
	mi := &file_compute_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMInfo) ProtoMessage() {}

func (x *VMInfo) ProtoReflect() protoreflect.Message {
	mi := &file_compute_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMInfo.ProtoReflect.Descriptor instead.
func (*VMInfo) Descriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{11}
}

func (x *VMInfo) GetHandle() int32 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *VMInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VMInfo) GetState() VMState {
	if x != nil {
		return x.State
	}
	return VMState_VM_STATE_UNSPECIFIED
}

func (x *VMInfo) GetVcpus() uint32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *VMInfo) GetMemoryMb() uint64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *VMInfo) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *VMInfo) GetDisks() []*DiskSpec {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *VMInfo) GetNics() []*NicSpec {
	if x != nil {
		return x.Nics
	}
	return nil
}

func (x *VMInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *VMInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type DiskSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	SizeGb        uint64                 `protobuf:"varint,2,opt,name=size_gb,json=sizeGb,proto3" json:"size_gb,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"` // qcow2, raw, zvol
	StoragePool   string                 `protobuf:"bytes,4,opt,name=storage_pool,json=storagePool,proto3" json:"storage_pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskSpec) Reset() {
	*x = DiskSpec{}
	mi := &file_compute_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskSpec) ProtoMessage() {}

func (x *DiskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_compute_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskSpec.ProtoReflect.Descriptor instead.
func (*DiskSpec) Descriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{12}
}

func (x *DiskSpec) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiskSpec) GetSizeGb() uint64 {
	if x != nil {
		return x.SizeGb
	}
	return 0
}

func (x *DiskSpec) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *DiskSpec) GetStoragePool() string {
	if x != nil {
		return x.StoragePool
	}
	return ""
}

type NicSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bridge        string                 `protobuf:"bytes,1,opt,name=bridge,proto3" json:"bridge,omitempty"`
	MacAddress    string                 `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"` // virtio, e1000
	VlanId        int32                  `protobuf:"varint,4,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NicSpec) Reset() {
	*x = NicSpec{}
	mi := &file_compute_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NicSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NicSpec) ProtoMessage() {}

func (x *NicSpec) ProtoReflect() protoreflect.Message {
	mi := &file_compute_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NicSpec.ProtoReflect.Descriptor instead.
func (*NicSpec) Descriptor() ([]byte, []int) {
	return file_compute_proto_rawDescGZIP(), []int{13}
}

func (x *NicSpec) GetBridge() string {
	if x != nil {
		return x.Bridge
	}
	return ""
}

func (x *NicSpec) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NicSpec) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *NicSpec) GetVlanId() int32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

var File_compute_proto protoreflect.FileDescriptor

const file_compute_proto_rawDesc = "" +
	"\n" +
	"\rcompute.proto\x12\x18hardcorevisor.compute.v1\"\xea\x01\n" +
	"\x0fCreateVMRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05vcpus\x18\x02 \x01(\rR\x05vcpus\x12\x1b\n" +
	"\tmemory_mb\x18\x03 \x01(\x04R\bmemoryMb\x12\x1f\n" +
	"\vtemplate_id\x18\x04 \x01(\tR\n" +
	"templateId\x128\n" +
	"\x05disks\x18\x05 \x03(\v2\".hardcorevisor.compute.v1.DiskSpecR\x05disks\x125\n" +
	"\x04nics\x18\x06 \x03(\v2!.hardcorevisor.compute.v1.NicSpecR\x04nics\"D\n" +
	"\x10CreateVMResponse\x120\n" +
	"\x02vm\x18\x01 \x01(\v2 .hardcorevisor.compute.v1.VMInfoR\x02vm\"@\n" +
	"\x10DestroyVMRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x05R\x06handle\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\x13\n" +
	"\x11DestroyVMResponse\")\n" +
	"\x0fVMActionRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x05R\x06handle\"R\n" +
	"\x10VMActionResponse\x12>\n" +
	"\tnew_state\x18\x01 \x01(\x0e2!.hardcorevisor.compute.v1.VMStateR\bnewState\"w\n" +
	"\x0eListVMsRequest\x12\x1f\n" +
	"\vnode_filter\x18\x01 \x01(\tR\n" +
	"nodeFilter\x12D\n" +
	"\fstate_filter\x18\x02 \x01(\x0e2!.hardcorevisor.compute.v1.VMStateR\vstateFilter\"E\n" +
	"\x0fListVMsResponse\x122\n" +
	"\x03vms\x18\x01 \x03(\v2 .hardcorevisor.compute.v1.VMInfoR\x03vms\"&\n" +
	"\fGetVMRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x05R\x06handle\"M\n" +
	"\x12LiveMigrateRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x05R\x06handle\x12\x1f\n" +
	"\vtarget_node\x18\x02 \x01(\tR\n" +
	"targetNode\"I\n" +
	"\x13LiveMigrateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe3\x02\n" +
	"\x06VMInfo\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x05R\x06handle\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x127\n" +
	"\x05state\x18\x03 \x01(\x0e2!.hardcorevisor.compute.v1.VMStateR\x05state\x12\x14\n" +
	"\x05vcpus\x18\x04 \x01(\rR\x05vcpus\x12\x1b\n" +
	"\tmemory_mb\x18\x05 \x01(\x04R\bmemoryMb\x12\x12\n" +
	"\x04node\x18\x06 \x01(\tR\x04node\x128\n" +
	"\x05disks\x18\a \x03(\v2\".hardcorevisor.compute.v1.DiskSpecR\x05disks\x125\n" +
	"\x04nics\x18\b \x03(\v2!.hardcorevisor.compute.v1.NicSpecR\x04nics\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\"r\n" +
	"\bDiskSpec\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x17\n" +
	"\asize_gb\x18\x02 \x01(\x04R\x06sizeGb\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12!\n" +
	"\fstorage_pool\x18\x04 \x01(\tR\vstoragePool\"q\n" +
	"\aNicSpec\x12\x16\n" +
	"\x06bridge\x18\x01 \x01(\tR\x06bridge\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x17\n" +
	"\avlan_id\x18\x04 \x01(\x05R\x06vlanId*\x93\x01\n" +
	"\aVMState\x12\x18\n" +
	"\x14VM_STATE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10VM_STATE_CREATED\x10\x01\x12\x17\n" +
	"\x13VM_STATE_CONFIGURED\x10\x02\x12\x14\n" +
	"\x10VM_STATE_RUNNING\x10\x03\x12\x13\n" +
	"\x0fVM_STATE_PAUSED\x10\x04\x12\x14\n" +
	"\x10VM_STATE_STOPPED\x10\x052\x80\a\n" +
	"\x0eComputeService\x12a\n" +
	"\bCreateVM\x12).hardcorevisor.compute.v1.CreateVMRequest\x1a*.hardcorevisor.compute.v1.CreateVMResponse\x12d\n" +
	"\tDestroyVM\x12*.hardcorevisor.compute.v1.DestroyVMRequest\x1a+.hardcorevisor.compute.v1.DestroyVMResponse\x12`\n" +
	"\aStartVM\x12).hardcorevisor.compute.v1.VMActionRequest\x1a*.hardcorevisor.compute.v1.VMActionResponse\x12_\n" +
	"\x06StopVM\x12).hardcorevisor.compute.v1.VMActionRequest\x1a*.hardcorevisor.compute.v1.VMActionResponse\x12`\n" +
	"\aPauseVM\x12).hardcorevisor.compute.v1.VMActionRequest\x1a*.hardcorevisor.compute.v1.VMActionResponse\x12a\n" +
	"\bResumeVM\x12).hardcorevisor.compute.v1.VMActionRequest\x1a*.hardcorevisor.compute.v1.VMActionResponse\x12^\n" +
	"\aListVMs\x12(.hardcorevisor.compute.v1.ListVMsRequest\x1a).hardcorevisor.compute.v1.ListVMsResponse\x12Q\n" +
	"\x05GetVM\x12&.hardcorevisor.compute.v1.GetVMRequest\x1a .hardcorevisor.compute.v1.VMInfo\x12j\n" +
	"\vLiveMigrate\x12,.hardcorevisor.compute.v1.LiveMigrateRequest\x1a-.hardcorevisor.compute.v1.LiveMigrateResponseBFZDgithub.com/HardcoreMonk/hardcorevisor/controller/pkg/proto/computepbb\x06proto3"

var (
	file_compute_proto_rawDescOnce sync.Once
	file_compute_proto_rawDescData []byte
)

func file_compute_proto_rawDescGZIP() []byte {
	file_compute_proto_rawDescOnce.Do(func() {
		file_compute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_compute_proto_rawDesc), len(file_compute_proto_rawDesc)))
	})
	return file_compute_proto_rawDescData
}

var file_compute_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_compute_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_compute_proto_goTypes = []any{
	(VMState)(0),                // 0: hardcorevisor.compute.v1.VMState
	(*CreateVMRequest)(nil),     // 1: hardcorevisor.compute.v1.CreateVMRequest
	(*CreateVMResponse)(nil),    // 2: hardcorevisor.compute.v1.CreateVMResponse
	(*DestroyVMRequest)(nil),    // 3: hardcorevisor.compute.v1.DestroyVMRequest
	(*DestroyVMResponse)(nil),   // 4: hardcorevisor.compute.v1.DestroyVMResponse
	(*VMActionRequest)(nil),     // 5: hardcorevisor.compute.v1.VMActionRequest
	(*VMActionResponse)(nil),    // 6: hardcorevisor.compute.v1.VMActionResponse
	(*ListVMsRequest)(nil),      // 7: hardcorevisor.compute.v1.ListVMsRequest
	(*ListVMsResponse)(nil),     // 8: hardcorevisor.compute.v1.ListVMsResponse
	(*GetVMRequest)(nil),        // 9: hardcorevisor.compute.v1.GetVMRequest
	(*LiveMigrateRequest)(nil),  // 10: hardcorevisor.compute.v1.LiveMigrateRequest
	(*LiveMigrateResponse)(nil), // 11: hardcorevisor.compute.v1.LiveMigrateResponse
	(*VMInfo)(nil),              // 12: hardcorevisor.compute.v1.VMInfo
	(*DiskSpec)(nil),            // 13: hardcorevisor.compute.v1.DiskSpec
	(*NicSpec)(nil),             // 14: hardcorevisor.compute.v1.NicSpec
}
var file_compute_proto_depIdxs = []int32{
	13, // 0: hardcorevisor.compute.v1.CreateVMRequest.disks:type_name -> hardcorevisor.compute.v1.DiskSpec
	14, // 1: hardcorevisor.compute.v1.CreateVMRequest.nics:type_name -> hardcorevisor.compute.v1.NicSpec
	12, // 2: hardcorevisor.compute.v1.CreateVMResponse.vm:type_name -> hardcorevisor.compute.v1.VMInfo
	0,  // 3: hardcorevisor.compute.v1.VMActionResponse.new_state:type_name -> hardcorevisor.compute.v1.VMState
	0,  // 4: hardcorevisor.compute.v1.ListVMsRequest.state_filter:type_name -> hardcorevisor.compute.v1.VMState
	12, // 5: hardcorevisor.compute.v1.ListVMsResponse.vms:type_name -> hardcorevisor.compute.v1.VMInfo
	0,  // 6: hardcorevisor.compute.v1.VMInfo.state:type_name -> hardcorevisor.compute.v1.VMState
	13, // 7: hardcorevisor.compute.v1.VMInfo.disks:type_name -> hardcorevisor.compute.v1.DiskSpec
	14, // 8: hardcorevisor.compute.v1.VMInfo.nics:type_name -> hardcorevisor.compute.v1.NicSpec
	1,  // 9: hardcorevisor.compute.v1.ComputeService.CreateVM:input_type -> hardcorevisor.compute.v1.CreateVMRequest
	3,  // 10: hardcorevisor.compute.v1.ComputeService.DestroyVM:input_type -> hardcorevisor.compute.v1.DestroyVMRequest
	5,  // 11: hardcorevisor.compute.v1.ComputeService.StartVM:input_type -> hardcorevisor.compute.v1.VMActionRequest
	5,  // 12: hardcorevisor.compute.v1.ComputeService.StopVM:input_type -> hardcorevisor.compute.v1.VMActionRequest
	5,  // 13: hardcorevisor.compute.v1.ComputeService.PauseVM:input_type -> hardcorevisor.compute.v1.VMActionRequest
	5,  // 14: hardcorevisor.compute.v1.ComputeService.ResumeVM:input_type -> hardcorevisor.compute.v1.VMActionRequest
	7,  // 15: hardcorevisor.compute.v1.ComputeService.ListVMs:input_type -> hardcorevisor.compute.v1.ListVMsRequest
	9,  // 16: hardcorevisor.compute.v1.ComputeService.GetVM:input_type -> hardcorevisor.compute.v1.GetVMRequest
	10, // 17: hardcorevisor.compute.v1.ComputeService.LiveMigrate:input_type -> hardcorevisor.compute.v1.LiveMigrateRequest
	2,  // 18: hardcorevisor.compute.v1.ComputeService.CreateVM:output_type -> hardcorevisor.compute.v1.CreateVMResponse
	4,  // 19: hardcorevisor.compute.v1.ComputeService.DestroyVM:output_type -> hardcorevisor.compute.v1.DestroyVMResponse
	6,  // 20: hardcorevisor.compute.v1.ComputeService.StartVM:output_type -> hardcorevisor.compute.v1.VMActionResponse
	6,  // 21: hardcorevisor.compute.v1.ComputeService.StopVM:output_type -> hardcorevisor.compute.v1.VMActionResponse
	6,  // 22: hardcorevisor.compute.v1.ComputeService.PauseVM:output_type -> hardcorevisor.compute.v1.VMActionResponse
	6,  // 23: hardcorevisor.compute.v1.ComputeService.ResumeVM:output_type -> hardcorevisor.compute.v1.VMActionResponse
	8,  // 24: hardcorevisor.compute.v1.ComputeService.ListVMs:output_type -> hardcorevisor.compute.v1.ListVMsResponse
	12, // 25: hardcorevisor.compute.v1.ComputeService.GetVM:output_type -> hardcorevisor.compute.v1.VMInfo
	11, // 26: hardcorevisor.compute.v1.ComputeService.LiveMigrate:output_type -> hardcorevisor.compute.v1.LiveMigrateResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_compute_proto_init() }
func file_compute_proto_init() {
	if File_compute_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_compute_proto_rawDesc), len(file_compute_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_compute_proto_goTypes,
		DependencyIndexes: file_compute_proto_depIdxs,
		EnumInfos:         file_compute_proto_enumTypes,
		MessageInfos:      file_compute_proto_msgTypes,
	}.Build()
	File_compute_proto = out.File
	file_compute_proto_goTypes = nil
	file_compute_proto_depIdxs = nil
}
