// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: compute.proto

package computepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ComputeService_CreateVM_FullMethodName    = "/hardcorevisor.compute.v1.ComputeService/CreateVM"
	ComputeService_DestroyVM_FullMethodName   = "/hardcorevisor.compute.v1.ComputeService/DestroyVM"
	ComputeService_StartVM_FullMethodName     = "/hardcorevisor.compute.v1.ComputeService/StartVM"
	ComputeService_StopVM_FullMethodName      = "/hardcorevisor.compute.v1.ComputeService/StopVM"
	ComputeService_PauseVM_FullMethodName     = "/hardcorevisor.compute.v1.ComputeService/PauseVM"
	ComputeService_ResumeVM_FullMethodName    = "/hardcorevisor.compute.v1.ComputeService/ResumeVM"
	ComputeService_ListVMs_FullMethodName     = "/hardcorevisor.compute.v1.ComputeService/ListVMs"
	ComputeService_GetVM_FullMethodName       = "/hardcorevisor.compute.v1.ComputeService/GetVM"
	ComputeService_LiveMigrate_FullMethodName = "/hardcorevisor.compute.v1.ComputeService/LiveMigrate"
)

// ComputeServiceClient is the client API for ComputeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComputeServiceClient interface {
	CreateVM(ctx context.Context, in *CreateVMRequest, opts ...grpc.CallOption) (*CreateVMResponse, error)
	DestroyVM(ctx context.Context, in *DestroyVMRequest, opts ...grpc.CallOption) (*DestroyVMResponse, error)
	StartVM(ctx context.Context, in *VMActionRequest, opts ...grpc.CallOption) (*VMActionResponse, error)
	StopVM(ctx context.Context, in *VMActionRequest, opts ...grpc.CallOption) (*VMActionResponse, error)
	PauseVM(ctx context.Context, in *VMActionRequest, opts ...grpc.CallOption) (*VMActionResponse, error)
	ResumeVM(ctx context.Context, in *VMActionRequest, opts ...grpc.CallOption) (*VMActionResponse, error)
	ListVMs(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error)
	GetVM(ctx context.Context, in *GetVMRequest, opts ...grpc.CallOption) (*VMInfo, error)
	LiveMigrate(ctx context.Context, in *LiveMigrateRequest, opts ...grpc.CallOption) (*LiveMigrateResponse, error)
}

type computeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewComputeServiceClient(cc grpc.ClientConnInterface) ComputeServiceClient {
	return &computeServiceClient{cc}
}

func (c *computeServiceClient) CreateVM(ctx context.Context, in *CreateVMRequest, opts ...grpc.CallOption) (*CreateVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVMResponse)
	err := c.cc.Invoke(ctx, ComputeService_CreateVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) DestroyVM(ctx context.Context, in *DestroyVMRequest, opts ...grpc.CallOption) (*DestroyVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyVMResponse)
	err := c.cc.Invoke(ctx, ComputeService_DestroyVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) StartVM(ctx context.Context, in *VMActionRequest, opts ...grpc.CallOption) (*VMActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMActionResponse)
	err := c.cc.Invoke(ctx, ComputeService_StartVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) StopVM(ctx context.Context, in *VMActionRequest, opts ...grpc.CallOption) (*VMActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMActionResponse)
	err := c.cc.Invoke(ctx, ComputeService_StopVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) PauseVM(ctx context.Context, in *VMActionRequest, opts ...grpc.CallOption) (*VMActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMActionResponse)
	err := c.cc.Invoke(ctx, ComputeService_PauseVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) ResumeVM(ctx context.Context, in *VMActionRequest, opts ...grpc.CallOption) (*VMActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMActionResponse)
	err := c.cc.Invoke(ctx, ComputeService_ResumeVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) ListVMs(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVMsResponse)
	err := c.cc.Invoke(ctx, ComputeService_ListVMs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) GetVM(ctx context.Context, in *GetVMRequest, opts ...grpc.CallOption) (*VMInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMInfo)
	err := c.cc.Invoke(ctx, ComputeService_GetVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeServiceClient) LiveMigrate(ctx context.Context, in *LiveMigrateRequest, opts ...grpc.CallOption) (*LiveMigrateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LiveMigrateResponse)
	err := c.cc.Invoke(ctx, ComputeService_LiveMigrate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComputeServiceServer is the server API for ComputeService service.
// All implementations must embed UnimplementedComputeServiceServer
// for forward compatibility.
type ComputeServiceServer interface {
	CreateVM(context.Context, *CreateVMRequest) (*CreateVMResponse, error)
	DestroyVM(context.Context, *DestroyVMRequest) (*DestroyVMResponse, error)
	StartVM(context.Context, *VMActionRequest) (*VMActionResponse, error)
	StopVM(context.Context, *VMActionRequest) (*VMActionResponse, error)
	PauseVM(context.Context, *VMActionRequest) (*VMActionResponse, error)
	ResumeVM(context.Context, *VMActionRequest) (*VMActionResponse, error)
	ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error)
	GetVM(context.Context, *GetVMRequest) (*VMInfo, error)
	LiveMigrate(context.Context, *LiveMigrateRequest) (*LiveMigrateResponse, error)
	mustEmbedUnimplementedComputeServiceServer()
}

// UnimplementedComputeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComputeServiceServer struct{}

func (UnimplementedComputeServiceServer) CreateVM(context.Context, *CreateVMRequest) (*CreateVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVM not implemented")
}
func (UnimplementedComputeServiceServer) DestroyVM(context.Context, *DestroyVMRequest) (*DestroyVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyVM not implemented")
}
func (UnimplementedComputeServiceServer) StartVM(context.Context, *VMActionRequest) (*VMActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartVM not implemented")
}
func (UnimplementedComputeServiceServer) StopVM(context.Context, *VMActionRequest) (*VMActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopVM not implemented")
}
func (UnimplementedComputeServiceServer) PauseVM(context.Context, *VMActionRequest) (*VMActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseVM not implemented")
}
func (UnimplementedComputeServiceServer) ResumeVM(context.Context, *VMActionRequest) (*VMActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeVM not implemented")
}
func (UnimplementedComputeServiceServer) ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVMs not implemented")
}
func (UnimplementedComputeServiceServer) GetVM(context.Context, *GetVMRequest) (*VMInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVM not implemented")
}
func (UnimplementedComputeServiceServer) LiveMigrate(context.Context, *LiveMigrateRequest) (*LiveMigrateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LiveMigrate not implemented")
}
func (UnimplementedComputeServiceServer) mustEmbedUnimplementedComputeServiceServer() {}
func (UnimplementedComputeServiceServer) testEmbeddedByValue()                        {}

// UnsafeComputeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComputeServiceServer will
// result in compilation errors.
type UnsafeComputeServiceServer interface {
	mustEmbedUnimplementedComputeServiceServer()
}

func RegisterComputeServiceServer(s grpc.ServiceRegistrar, srv ComputeServiceServer) {
	// If the following call panics, it indicates UnimplementedComputeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ComputeService_ServiceDesc, srv)
}

func _ComputeService_CreateVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).CreateVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_CreateVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).CreateVM(ctx, req.(*CreateVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_DestroyVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).DestroyVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_DestroyVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).DestroyVM(ctx, req.(*DestroyVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_StartVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).StartVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_StartVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).StartVM(ctx, req.(*VMActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_StopVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).StopVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_StopVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).StopVM(ctx, req.(*VMActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_PauseVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).PauseVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_PauseVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).PauseVM(ctx, req.(*VMActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_ResumeVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).ResumeVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_ResumeVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).ResumeVM(ctx, req.(*VMActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_ListVMs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVMsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).ListVMs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_ListVMs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).ListVMs(ctx, req.(*ListVMsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_GetVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).GetVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_GetVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).GetVM(ctx, req.(*GetVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeService_LiveMigrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LiveMigrateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServiceServer).LiveMigrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeService_LiveMigrate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServiceServer).LiveMigrate(ctx, req.(*LiveMigrateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ComputeService_ServiceDesc is the grpc.ServiceDesc for ComputeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComputeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hardcorevisor.compute.v1.ComputeService",
	HandlerType: (*ComputeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVM",
			Handler:    _ComputeService_CreateVM_Handler,
		},
		{
			MethodName: "DestroyVM",
			Handler:    _ComputeService_DestroyVM_Handler,
		},
		{
			MethodName: "StartVM",
			Handler:    _ComputeService_StartVM_Handler,
		},
		{
			MethodName: "StopVM",
			Handler:    _ComputeService_StopVM_Handler,
		},
		{
			MethodName: "PauseVM",
			Handler:    _ComputeService_PauseVM_Handler,
		},
		{
			MethodName: "ResumeVM",
			Handler:    _ComputeService_ResumeVM_Handler,
		},
		{
			MethodName: "ListVMs",
			Handler:    _ComputeService_ListVMs_Handler,
		},
		{
			MethodName: "GetVM",
			Handler:    _ComputeService_GetVM_Handler,
		},
		{
			MethodName: "LiveMigrate",
			Handler:    _ComputeService_LiveMigrate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compute.proto",
}
